# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 4.5'
pod 'AlamofireImage', '~> 3.3'
pod "RappleProgressHUD"
pod 'SwiftyJSON'
pod 'Kingfisher'

  # Pods for WeatherApp

end
